# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3

    working_directory: ~/main

    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: sudo apt-get install python-dev && sudo apt-get install python-pip && sudo pip install awscli
      - run: 
          name: AWS CLI Version
          command: aws --version
      - run:
          name: Lint Wordshop Web and Api
          command: ./lint.sh
      - run: 
          name: Build Wordshop Web and Api
          command: NG_CLI_ANALYTICS=ci ./build.sh
      - deploy:
          name: Deploy Wordshop Web and Api
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ./deploy.sh
            else
              echo "Not master branch so not deploying WordShop Web and Api"
            fi